### ISSUE TITLE
Can't find PCB X2 part

### ISSUE THREAD

**Issue by StrangePigeon79** [3DChameleon/3DChameleonMk4#2]
If I can't find the 16Mhz (X2) part for ordering the pcb, what can I use instead? Nothing has the "OSC-SMD_4P-L3.2-W2.5-H1.0" leg in the options
![image](https://github.com/user-attachments/assets/090a0f67-020c-4abd-80bc-eeb56e9c4cfc)

**Comment by wjsteele** [comment]
It’s a common package, 3.2 X 2.5mm… there are many suitable replacements for it. You can even go up to 20mhz as well, but you’d have to change the fuse settings.

Qantek and ICD are names that comes to mind.

Bill

On Dec 4, 2024, at 8:56 AM, Sir Cogwheel ***@***.***> wrote:

﻿

If I can't find the 16Mhz (X2) part for ordering the pcb, what can I use instead? Nothing has the "OSC-SMD_4P-L3.2-W2.5-BL" leg.
image.png (view on web)<https://github.com/user-attachments/assets/090a0f67-020c-4abd-80bc-eeb56e9c4cfc>
